name: 'Semver Conventional Commits'
description: 'Calculate the next release version based on conventional commits since latest tag'
author: Nathan Tamez
inputs:
  token:
    description: GitHub Token
    required: true
  branch:
    description: The branch to use when fetching list of commits to compare against
    required: false
    default: main
  majorList:
    description: Comma separated commit prefixes, used to bump Major version
    required: false
    default: ''
  minorList:
    description: Comma separated commit prefixes, used to bump Minor version
    required: false
    default: feat, feature
  patchList:
    description: Comma separated commit prefixes, used to bump Patch version
    required: false
    default: fix, bugfix, perf, refactor, test, tests
  patchAll:
    description: If set to true, will ignore patchList and count any commit as a Patch
    required: false
    default: 'false'
  skipInvalidTags:
    description: If set to true, will skip tags that are not valid semver until it finds a proper one (up to 10 from latest).
    required: false
    default: 'false'
  noVersionBumpBehavior:
    description: Whether to exit with an error, warning or silently when none of the commits result in a version bump. (error, warn, current, silent)
    required: false
    default: error
  preReleaseStage:
    description: The Pre Release Stage to use, (rc, beta, alpha, etc)
    required: false
    default: none
  prefix:
    description: A prefix that will be ignored when parsing tags. Useful for monorepos. The prefix will be added back to the output values.
    required: false
    default: ''
  squashMergeCommitMessage:
    description: if set to a valid commit message, will calculate semver based on this commit message instead of the list of commits. Useful for squash merges.
    required: false
  additionalCommits:
    description: A list of additional commit messages to parse in order to calculate semver.
    required: false
  fromTag:
    description: Override the tag to use when comparing against the branch in order to fetch the list of commits.
    required: false
    default: ''
  minimumChange:
    description: The minimum change to bump the version. the change must be greater than this value. (major, minor, patch, none)
    required: false
    default: none
outputs:
  current:
    description: Current version number / latest tag.
  next:
    description: Next version number in format v0.0.0
  nextStrict:
    description: Next version number without the v prefix.
  nextMajor:
    description: Next version major number in format v0
  nextMajorStrict:
    description: Next version major number only.
  versionType:
    description: The type of version bump
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: fast-forward
  color: red
